"""
Fleet management API — paginated, gated telemetry.
"""
import math
import random
import structlog
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from app.core.database import get_db
from app.core.pagination import PageParams, Page
from app.api.auth import get_current_user
from app.models.user import User
from app.models.uav import UAV, UAVStatus, UAVClass
from app.schemas.uav import UAVCreate, UAVUpdate, UAVResponse, TelemetrySnapshot

logger = structlog.get_logger()
router = APIRouter()


# ── List + pagination ─────────────────────────────────────────────

@router.get("/", response_model=Page[UAVResponse])
async def list_fleet(
    params:       PageParams    = Depends(),
    status_filter:str | None   = Query(None, alias="status"),
    uav_class:    str | None   = Query(None),
    current_user: User          = Depends(get_current_user),
    db:           AsyncSession  = Depends(get_db),
):
    q = select(UAV).where(UAV.owner_id == current_user.id)
    if status_filter:
        try:
            q = q.where(UAV.status == UAVStatus(status_filter.upper()))
        except ValueError:
            raise HTTPException(400, f"Invalid status '{status_filter}'")
    if uav_class:
        try:
            q = q.where(UAV.uav_class == UAVClass(uav_class.upper()))
        except ValueError:
            raise HTTPException(400, f"Invalid class '{uav_class}'")

    total_r = await db.execute(select(func.count()).select_from(q.subquery()))
    total   = total_r.scalar() or 0

    q = q.order_by(UAV.created_at).limit(params.limit).offset(params.offset)
    result  = await db.execute(q)
    items   = result.scalars().all()

    return Page.of(items, total, params)


@router.post("/", response_model=UAVResponse, status_code=status.HTTP_201_CREATED)
async def create_uav(
    payload:      UAVCreate,
    current_user: User         = Depends(get_current_user),
    db:           AsyncSession = Depends(get_db),
):
    # Limit fleet size per user
    count_r = await db.execute(
        select(func.count()).where(UAV.owner_id == current_user.id)
    )
    if (count_r.scalar() or 0) >= 100:
        raise HTTPException(400, "Fleet limit reached (max 100 UAVs)")

    uav = UAV(owner_id=current_user.id, **payload.model_dump())
    db.add(uav)
    await db.commit()
    await db.refresh(uav)
    logger.info("fleet.uav_created", id=uav.id, callsign=uav.callsign, user=current_user.id)
    return uav


@router.get("/stats")
async def fleet_stats(
    current_user: User         = Depends(get_current_user),
    db:           AsyncSession = Depends(get_db),
):
    total_r = await db.execute(
        select(func.count()).where(UAV.owner_id == current_user.id)
    )
    total = total_r.scalar() or 0

    online_r = await db.execute(
        select(func.count()).where(
            UAV.owner_id == current_user.id,
            UAV.status.in_([UAVStatus.ONLINE, UAVStatus.IN_MISSION]),
        )
    )
    active = online_r.scalar() or 0

    mission_r = await db.execute(
        select(func.count()).where(
            UAV.owner_id == current_user.id,
            UAV.status == UAVStatus.IN_MISSION,
        )
    )
    in_mission = mission_r.scalar() or 0

    return {
        "total":      total,
        "active":     active,
        "offline":    total - active,
        "in_mission": in_mission,
    }


@router.get("/telemetry", response_model=list[TelemetrySnapshot])
async def fleet_telemetry(
    current_user: User         = Depends(get_current_user),
    db:           AsyncSession = Depends(get_db),
):
    """
    Telemetry only for ONLINE or IN_MISSION UAVs.
    Positions generated by broadcaster; this endpoint returns a snapshot.
    IDLE/OFFLINE UAVs return no data — they are not flying.
    """
    result = await db.execute(
        select(UAV).where(
            UAV.owner_id == current_user.id,
            UAV.status.in_([UAVStatus.ONLINE, UAVStatus.IN_MISSION]),
        )
    )
    uavs = result.scalars().all()

    # Pull from broadcaster cache if available
    from app.simulation.telemetry_broadcaster import get_uav_state
    snapshots = []
    for uav in uavs:
        state = get_uav_state(uav.id)
        if state:
            snapshots.append(TelemetrySnapshot(
                uav_id=uav.id, callsign=uav.callsign, status=uav.status,
                lat=state["lat"], lon=state["lon"],
                altitude_m=state["altitude_m"], speed_ms=state["speed_ms"],
                heading_deg=state["heading_deg"], battery_pct=state["battery_pct"],
                link_quality=state["link_quality"],
                timestamp=datetime.now(timezone.utc).isoformat(),
            ))
    return snapshots


@router.get("/{uav_id}", response_model=UAVResponse)
async def get_uav(
    uav_id:       str,
    current_user: User         = Depends(get_current_user),
    db:           AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(UAV).where(UAV.id == uav_id, UAV.owner_id == current_user.id)
    )
    uav = result.scalar_one_or_none()
    if not uav:
        raise HTTPException(404, "UAV not found")
    return uav


@router.patch("/{uav_id}", response_model=UAVResponse)
async def update_uav(
    uav_id:       str,
    payload:      UAVUpdate,
    current_user: User         = Depends(get_current_user),
    db:           AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(UAV).where(UAV.id == uav_id, UAV.owner_id == current_user.id)
    )
    uav = result.scalar_one_or_none()
    if not uav:
        raise HTTPException(404, "UAV not found")

    for field, value in payload.model_dump(exclude_none=True).items():
        setattr(uav, field, value)
    await db.commit()
    await db.refresh(uav)
    return uav


@router.delete("/{uav_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_uav(
    uav_id:       str,
    current_user: User         = Depends(get_current_user),
    db:           AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(UAV).where(UAV.id == uav_id, UAV.owner_id == current_user.id)
    )
    uav = result.scalar_one_or_none()
    if not uav:
        raise HTTPException(404, "UAV not found")
    await db.delete(uav)
    await db.commit()
